### ISSUE TITLE
external prx file

### ISSUE THREAD

**Issue by rofl0r** [NT-Bourgeois-Iridescence-Technologies/MElib#1]
hi, i was wondering whether there's a specific reason the mediaengine.prx is a separate file that needs to be shipped together with the program using it, as opposed to be statically linked into libME.a (and by that, the user of libME) ?

**Comment by IridescentRose** [comment]
mediaengine PRX is a compiled separate binary driver from the target application which needs to be loaded in kernel mode (whereas the user program is in user mode). This distinction necessitates the inclusion of a separate binary much like how you would interface with a device driver on modern operating systems.
